#+title: 战略


* <2022-08-29 Mon>
** 改变对 Emacs 的看法，找回了最初的目标
: Emacs 只是我实现 "一切皆编辑" 的工具罢了。

我发觉了自己把 emacs 当成自己的精神寄托，是多么傻的一件行为。所以在我删除了 doom-emacs, 我还是把它下回来了，这次无关信仰，是暂时还没有找到替代品，能够承担我的期望：” 通过编辑来提高效率"。

只有 emacs 有这么强大的功能。 准确的说，是 doom-emacs.

所以我很后悔今年暑假有段时间把 doom-emacs 卸载了，重装了懒猫，陈斌的 emacs, 最后又换回了 doom-emacs, 按照道理说，他们的 emacs 其实更适合学习。但是我现在确认我只是需要一款可以实现“通过编辑学习”的编辑器罢了，否则去用 vim 了，我对学习 emacs 根本没有兴趣。

所以 doom-emacs 配置多么复杂，在公司内网用不了，对学习不利，还是什么，都无所谓了，我想着自己 fork 一份，也许作者自己不维护了，我也能继续在破电脑上用 doom-emacs 实现那个目标。

** 彻底承认过去的失败 : 我根本不会自学
: 只是我不想学；把时间都用到了 xxoo 科目上而已，而哪科又太难，我还没有成果 / 导致我有知识盲区；我对于那科研究的更加深入，我看得书都是更难的，考试的反而不会写；应试考试只是纸老虎，挂了就挂了，证明不了什么；考试前一天还在做自己的事（写代码）等等。

以上是我对于大学找的诸多借口，骗了自己很久，如今没有意思了，我应该坦率的承认自己的错误。我上面的那些只是借口，真正的原因只有一个：我根本不会自学。

我毫无自学能力，我周围的人也许也没有，但是他们听老师的话啊，我既不虚心听讲，孤僻高傲。导致了种种问题。

我彻底承认我过去所做的，自以为的努力都是浪费时间。（别人浪不浪费 / 效率高不高我不知道，但是我知道我挺低的）

** 新的学习方法
*** 控制身体行为，让身体时刻蓄满能量。
*** 最大程度的强化学习效率
**** 以时间为驱动式
过去的战略的彻底失败，就是心情驱动，导致一叶樟目。单科效率低，多科 gg. 不敢面对自己的弱项，毫无进步。
**** 充分刺激大脑
***** 合理划分时间
如果 40 分钟学习了英语口语，则不应该在继续把时间划分为 4 级单词背诵。

***** 在单科继续划分
****** 预习时间
快速过一遍
****** 穿插回溯
借助 vim 的指法，快速输出
****** 思考时间
什么都不要动，想。

一定要把问题限定好范围，防止思维发散
****** 复习
非常重要。
有小复，大复，中复

**** 学习的最好方法就是，逐渐分解成任务驱动
** 决定重新吃药
我决定重新把药吃回去。其实不久之前也还在吃啊，为什么都没好？
也许是没有运动（没有合理的时间安排运动？？），我不知道，但是我没有选择。
我唯一令我安慰的是，我现在会 gtd, 学会把问题记录下来，针对性地解决。也许这次能好？
** Emacs 的工作流
*** Workspace 适合辅助
: 我一直使用 doom-emacs, 因为很喜欢其 workspace, 但是我发现我把他作为我的 workflow 恐怖是不合适的。
**** 不适合 master
我过去也有任务驱动的苗头，方式是借助 workspace, 把什么东西，甚至是 eaf-buffer 都分成 workspace, 的确是清晰了。但是过于分散，导致心智负担。
例如，我打开了一个 workspace, 那我什么时候切换其他任务呢？下一个任务 / Worksapce 由上一个负责？
**** 缺少它不行
即使只打开 2-3 个，或者开了就关。但是它的存在，确实保证了布局的干净。
*** GTD
: 我发现了 GTD, GTD 主 Master 才是正确的。
主 Workspace 是可以迁移的，用来存放发号施令的 gtd-master, 以至于脱离 doom-emacs.
* <2022-08-30 Tue>
** 需要改变自己在运动理论上的素养
多增加对运动的知识
* <2022-08-31 Wed>
** 我找到了一种适合我锻炼的方式，且拥有非常大程度的自由
那就是深蹲，没有错，我以前一直忽视了自重深蹲。
我发现自重深蹲对于 *非职业运动员* ，仅仅像我这样的时间管理大师来说，非常有用。
从此之后，我保证，我的时间管理绝对会更加紧凑，不会在出现，中午没有去锻炼，然后下午去，然后又喝水，晚上又吃宵夜，把计划破坏的情况。
* <2022-09-01 Thu>
** 分段锻炼和分段吃是不合理的。
*** 锻炼应该一口气做玩，而不是每隔多少分钟困了再去做？困了去做的应该叫散步，因为你人已经很困了，就应该放松，而不是累。
因为这样锻炼既没有效率，同时也无法起到提神的作用，而且还容易给别人造成麻烦。
*** 去买几个干蒸，几个肉包子，等多少分钟吃一次。这样的方法是不合理，最后都会失败收场
